### ISSUE TITLE
Get shared folder url in public directory

### ISSUE THREAD

**Issue by gety9** [Alorel/dropbox-v2-php#12]
Hi,

I have public dropbox directory that have folder photos, photos folder have folders with numeric names 193112910, 193112911, 193112912, etc.

(public>photos>193112XXX)

I need to get dropbox link for numeric folders. For example i pass 193112910 parameter, and want to get dropbox link for this folder. For example https://www.dropbox.com/sh/XXXXy0v3xbry7yd/AABeBvWMaqXXXXcQAEVhSQza?dl=0

Can i do that using your SDK?

**Comment by Alorel** [comment]
Hey. Anything you can do with [these API endpoints](https://www.dropbox.com/developers/documentation/http/documentation) you can also do with the SDK - it's just a PHP wrapper around the Dropbox API.
