### ISSUE TITLE
Invalid authorization value in HTTP header

### ISSUE THREAD

**Issue by w4ng101** [Alorel/dropbox-v2-php#13]
Hi Art,

Can you help me this issue's?

Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://content.dropboxapi.com/2/files/upload` resulted in a `400 Bad Request` response: Error in call to API function "files/upload": Invalid authorization value in HTTP header "Authorization": "Bearer 163{\" (truncated...) ' in C:\xampp\htdocs\dropbox-v2-php\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113 Stack trace: #0 C:\xampp\htdocs\dropbox-v2-php\vendor\guzzlehttp\guzzle\src\Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 C:\xampp\htdocs\dropbox-v2-php\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 C:\xampp\htdocs\dropbox-v2-php\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 C:\xampp\htdocs\dropbox-v2-php\vendor\guzzlehttp\promises\src\TaskQ in C:\xampp\htdocs\dropbox-v2-php\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113

**Comment by Alorel** [comment]
You need to set the Dropbox API access token before you can make API calls. You can either do this for every class manually, or globally as described in the [readme](https://github.com/Alorel/dropbox-v2-php#usage).

**Comment by w4ng101** [comment]
Hi Art,

Yes I've been solve the issue's do you have an example upload large files like folder,zip etc.

**Comment by anuar101** [comment]
Then I've been using Upload.md guide but the images files successfully uploaded but the result was like this 
![image](https://user-images.githubusercontent.com/11203478/31206253-33a694be-a9a9-11e7-88ff-299c46523c36.png)

**Comment by Alorel** [comment]
https://github.com/Alorel/dropbox-v2-php/blob/master/examples/Raw/Files/UploadSession.md

**Comment by w4ng101** [comment]
Yeah I've been using that thanks Arl :)

**Comment by anuar101** [comment]
Hi Art,

Can you help me I've been using UploadSession function it's working fine in my localhost nothing issue's but during testing in live server i found an issue "HTTP ERROR 500". I've been already check all libraries so far it's working but  this process

 // Keep appending until we're at the last segment
                    while (!$finished) {
                        $cursor->setOffset($offset);
                        $data = \GuzzleHttp\Psr7\stream_for($fh->read($buffer));
                        $offset += $buffer;

                        if ($data->getSize() == $buffer || $offset < $filesize) {
                            // Haven't scanned the entire file
                            $append->raw($data, $cursor);
                        } else {
                            //Send the last segment
                            $finished = true;
                            $commit = new CommitInfo($destinationPath);
                            (new Finish())->raw($data,$cursor,$commit);
                        }
                    }

i got an error.

Thanks,
Anuar

**Comment by anuar101** [comment]
Hi Arl,

I'll review my code i found out this line "(new Finish())->raw($data,$cursor,$commit);" causes an error "HTTP ERROR 500" during testing in linux live server. Can you help me?

Thanks,
Anuar
