### ISSUE TITLE
How to authorize the user?

### ISSUE THREAD

**Issue by immu** [Alorel/dropbox-v2-php#14]
Hey Alorel,

I was going through the following example :
dropbox-v2-php > examples > Raw > Files > Upload.md  
https://github.com/immu/dropbox-v2-php/blob/master/examples/Raw/Files/Upload.md

I wanted to understand, how to authorize a user if I already have access token, secret key. I didn't find document to this

I'm sorry for the 'bug' label, the correct label should be 'Question' 

Thanks & Regards,
Imran

**Comment by Alorel** [comment]
You put the token into the constructor.

https://github.com/Alorel/dropbox-v2-php#usage
