### ISSUE TITLE
"HTTP ERROR 500"

### ISSUE THREAD

**Issue by w4ng101** [Alorel/dropbox-v2-php#15]
Hi Arl,

I'll review my code i found out this line "(new Finish())->raw($data,$cursor,$commit);" causes an error "HTTP ERROR 500" during testing in linux live server. Can you help me?

Thanks,
Anuar

**Comment by w4ng101** [comment]
Hi Arl,

I've fixed the issue's please remove this "..." in line 120 "public static function merge(...$options) {" inside the files "dropbox-v2-php/src/Options/Options.php" because linux server is not working (but in windows server i think it is working, anyway i'm not sure!).

Thanks,
Anuar

**Comment by Alorel** [comment]
Upgrade your installation to use PHP 5.6 or newer. https://secure.php.net/manual/en/functions.arguments.php#functions.variable-arg-list

**Comment by Alorel** [comment]
The code's [tests](https://travis-ci.org/Alorel/dropbox-v2-php/builds) run every night and pass. [99.42% of all the code](https://codecov.io/gh/Alorel/dropbox-v2-php) is tested, so the problem is in your code, not the library's.

**Comment by w4ng101** [comment]
Hi Arl,

I'm not sure if the php version cause i'm using
![image](https://user-images.githubusercontent.com/11203478/31363317-4290f95c-ad90-11e7-8c62-537470aab566.png)
But anyway my issue was solved thanks a lot Arl :)

Thanks,
Anuar
