### ISSUE TITLE
How to catch error or show status

### ISSUE THREAD

**Issue by vulieumang** [Alorel/dropbox-v2-php#3]
in this document
https://www.dropbox.com/developers/documentation/http/documentation#files-save_url-check_job_status
by using curl we can have see error in command

```
curl -X POST https://api.dropboxapi.com/2/files/save_url \
    --header "Authorization: Bearer EXDuL6Bkvc4AAAAAAAABu-ZDfXZ0FRw87e00zjkrDbK2Rw_UpEGqlA-hz_tDgS3W" \
    --header "Content-Type: application/json" \
    --data "{\"path\": \"/a.jpg\",\"url\": \"https://igcdn-photos-e-a.akamaihd.net/hphotos-ak-xat1/t51.2885-15/e15/13398575_977722398990188_1841788166_n.jpg
\"}"
```

![image](https://cloud.githubusercontent.com/assets/13487753/16170150/2085052e-3573-11e6-96e2-378bd97870a4.png)
and now we see error in command
`Error in call to API function "files/save_url": request body: could not decode input as JSON
`
and how to see in browser
I was set ini_set('display_errors', 1);

**Comment by Alorel** [comment]
I am here to provide support with the library, not curl.

**Comment by vulieumang** [comment]
I mean is how to show error in this library, i can't see error when use lib and i don't know why it happen.
Then i use curl to check, i see error,  i think this lib have way to show error.
With this code i only see 
`Not saved yet - waiting for 3 seconds before checking for the job status 

``` php
if (isset($resp['async_job_id'])) {
            $check = new CheckJobStatus();

            do {
                echo 'Not saved yet - waiting for 3 seconds before checking for the job status' . PHP_EOL;
                sleep(3); //Wait a bit
                $r = json_decode($check->raw($resp['async_job_id'])->getBody()->getContents(), true);
            } while (isset($r['.tag']) && $r['.tag'] == 'in_progress');

            echo 'URL saved';
            } else {
            echo 'URL saved';

        }
```

that is my mean, i not good about type but i has find in example in this lib to show error, and i have stuck.

**Comment by Alorel** [comment]
Read the Dropbox API docs about why this is needed. If there was an actual error an exception would be thrown.
