### ISSUE TITLE
Authentication examples

### ISSUE THREAD

**Issue by dev4press** [Alorel/dropbox-v2-php#5]
Hi,

Thanks for the V2 API implementation!

I have checked examples provided, but I can't find the whole process that includes authentication (including getting the access token - with and without redirection to paste the token back into app asking for access). Am I missing something?

Milan

**Comment by Alorel** [comment]
Hi.

The SDK does not cover authentication and only acts as a wrapper for API calls. The authentication workflow is [fairly simple](https://www.dropbox.com/developers/reference/oauth-guide) - essentially make a link to your app's authorisation URL and, when the user is redirected back to your site, store the token for future use.

**Comment by dev4press** [comment]
Thanks!
