### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by AllegroBarry** [Alorel/dropbox-v2-php#7]
Hello, I'm trying to install your dropbox api and get the following error. Any ideas?:

fuji:photos root# $PHP5 composer.phar require alorel/dropbox-v2-php
Using version ^0.3.3 for alorel/dropbox-v2-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
- Installing aloframework/common (1.3.3)
  Downloading: 100%         
- Installing psr/http-message (1.0.1)
  Downloading: 100%         

Installation failed, reverting ./composer.json to its original content.

  [ErrorException]  
  copy(/santa/home/Allegro/customers/Frantz/photos/vendor/composer/0b15cccd/php-fig-http-message-f6561bf/._CHANGELOG.  
  md): failed to open stream: No such file or directory                                                                

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

fuji:photos root#

**Comment by Alorel** [comment]
Hm, I've never experienced this error. What's your php version?  Could you try installing it with PHP7?

**Comment by AllegroBarry** [comment]
Here you go...

fuji:photos root# echo $PHP7
/opt/local/bin/php70
fuji:photos root# $PHP7 --version
PHP 7.0.10 (cli) (built: Aug 20 2016 10:33:58) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
fuji:photos root# 
fuji:photos root# $PHP7 composer.phar require alorel/dropbox-v2-php
Using version ^0.3.3 for alorel/dropbox-v2-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
- Installing psr/http-message (1.0.1)
  Loading from cache

Installation failed, reverting ./composer.json to its original content.

  [ErrorException]  
  copy(/santa/home/Allegro/customers/Frantz/photos/vendor/composer/094913a8/php-fig-http-message-f6561bf/._CHANGELOG.  
  md): failed to open stream: No such file or directory                                                                

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

fuji:photos root#

**Comment by AllegroBarry** [comment]
Maybe if you could provide a simple tar or tar.gz file that we could download and expand, then we could get your api package without needing composer?

**Comment by Alorel** [comment]
Hm, I think you might need to clear your composer cache

```
{lamb} composer require alorel/dropbox-v2-php
Using version ^0.3.3 for alorel/dropbox-v2-php
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing aloframework/common (1.3.3)
    Loading from cache

  - Installing psr/http-message (1.0.1)
    Downloading: 100%

  - Installing guzzlehttp/psr7 (1.3.1)
    Loading from cache

  - Installing guzzlehttp/promises (1.2.0)
    Loading from cache

  - Installing guzzlehttp/guzzle (6.2.1)
    Loading from cache

  - Installing alorel/dropbox-v2-php (0.3.3)
    Loading from cache

Writing lock file
Generating autoload files
```

Composer _needs_ to be used due to this package's dependencies. In the meantime, you can use [this](https://github.com/Alorel/dropbox-v2-php/releases/download/0.3.3/dropbox-v2-php-0.3.3.zip) ZIP, which is a result of the above installation.

**Comment by AllegroBarry** [comment]
On 8/29/16 9:57 AM, Art wrote:

> Hm, I think you might need to clear your composer cache

Why would I need to do that? I installed composer for the sole and 
express purpose of installing your api. Before that I had never used 
composer. If composer's cache needs to be cleared, then it's due to 
something that happened as a result of trying to install your api.

Ok, let's assume clearing the composer cache is a worthwhile exercise... 
how do I do that?

Thanks,
Barry

> {lamb} composer require alorel/dropbox-v2-php
> Using version ^0.3.3 for alorel/dropbox-v2-php
> ./composer.json has been created
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> - Installing aloframework/common (1.3.3)
>    Loading from cache
> - Installing psr/http-message (1.0.1)
>    Downloading: 100%
> - Installing guzzlehttp/psr7 (1.3.1)
>    Loading from cache
> - Installing guzzlehttp/promises (1.2.0)
>    Loading from cache
> - Installing guzzlehttp/guzzle (6.2.1)
>    Loading from cache
> - Installing alorel/dropbox-v2-php (0.3.3)
>    Loading from cache
> 
> Writing lock file
> Generating autoload files
> 
> ```
> 
> Composer _needs_ to be used due to this package's dependencies. In the meantime, you can use this ZIP, which is a result of the above installation
> [dropbox.zip](https://github.com/Alorel/dropbox-v2-php/files/442948/dropbox.zip)
> ```

**Comment by Alorel** [comment]
It's just an assumption because the psr/http-message was being installed from cache and causing the exception. You can clear the cache using the `composer clear-cache` command.

**Comment by AllegroBarry** [comment]
On 8/29/16 10:16 AM, Art wrote:

> It's just an assumption because the psr/http-message was being installed from
> cache and causing the exception. You can clear the cache using the `composer
> clear-cache` command.

Thanks.

Unfortunately it made no difference (see below). I'll take a look at 
your zip file.

fuji:photos root# $PHP7 composer.phar clear-cache
Clearing cache (cache-dir): /private/var/root/.composer/cache
Clearing cache (cache-files-dir): /private/var/root/.composer/cache/files
Clearing cache (cache-repo-dir): /private/var/root/.composer/cache/repo
Cache directory does not exist (cache-vcs-dir):
All caches cleared.
fuji:photos root#
fuji:photos root# $PHP7 composer.phar require alorel/dropbox-v2-php
Using version ^0.3.3 for alorel/dropbox-v2-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
- Installing psr/http-message (1.0.1)
   Downloading: 100%

Installation failed, reverting ./composer.json to its original content.

   [ErrorException] 

copy(/santa/home/Allegro/customers/Frantz/photos/vendor/composer/2102c013/php-fig-http-message-f6561bf/._CHANGELOG. 

   md): failed to open stream: No such file or directory 

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] 
[--no-update] [--no-scripts] [--update-no-dev] 
[--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] 
[--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] 
[-a|--classmap-authoritative] [--] [<packages>]...

fuji:photos root#

**Comment by Alorel** [comment]
Hm, in that case you're best off raising an issue with [the folks behind composer](https://github.com/composer/composer) - I think they'd be much more competent at troubleshooting this.
