### ISSUE TITLE
Conflict Folder Already exists

### ISSUE THREAD

**Issue by Fabr9193** [Alorel/dropbox-v2-php#8]
Hello, 

As said in the title I have an issue with your type of return when a folder is already existing, is there a way to "override" your Error Handler without touching your code or do i have to change it ?

Thank you in advance, 

Fabricio

**Comment by Alorel** [comment]
Hi and sorry for the late reply.

I did not add any error handlers to this library. Could you please give me:

- The full exception stack trace
- Steps required to reproduce the issue
- Any system information that might be relevant, e.g. your operating system and PHP version.

**Comment by Fabr9193** [comment]
Sure i'll send you this right away

**Comment by Fabr9193** [comment]
![dropbox error two](https://cloud.githubusercontent.com/assets/5013061/22877123/35db11a2-f1d4-11e6-9d88-55c8f95cbb4e.PNG)
![dropbox error](https://cloud.githubusercontent.com/assets/5013061/22877122/35db05fe-f1d4-11e6-8722-35cac6b2fafb.PNG)


What i do here is that i fill a form with my Dropbox developer credentials and i try to create a FolderTree, The first folder is name Inochi but this folder already exists and that's what the code send to me.

I use PHP7 and wamp with MySQL v 5.6.34 Under Windows 10 Anniversary update.

Thanks for your help.

**Comment by Alorel** [comment]
It's an API error, not a library error. Refer [here](https://www.dropbox.com/developers/documentation/http/documentation#files-create_folder).

**Comment by Fabr9193** [comment]
Oh Thanks ! 
But how I handle this ? Just a Catch of CreateFolderError and i can do what i wish ( like remove the folder for example ? )

**Comment by Alorel** [comment]
Pretty much sums it up, yes.

**Comment by Fabr9193** [comment]
Oh alright i'm pretty new to PHP would that code work ? 

```
catch (DropboxException $exception)
        {
            if ($exception->getCode() == 409)
            {

                dump($exception->getTrace());
                return false;
            }

```

**Comment by Alorel** [comment]
I'd check for the exact error as the code might change over time (it's controlled by Dropbox) and/or have multiple errors mapping to the same code.

The basic workflow would be:

- [json_decode](https://secure.php.net/manual/en/function.json-decode.php) the response
- Check what the exact error is (see attachment)

![image](https://cloud.githubusercontent.com/assets/4998038/22882101/77ae2f08-f1e1-11e6-894b-349cf814d760.png)
